# Generated by Django 2.1.5 on 2019-07-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SimplifiedName', models.CharField(max_length=50)),
                ('TraditionalName', models.CharField(max_length=50)),
                ('PinyinName', models.CharField(max_length=50)),
                ('EnglishName_1', models.CharField(max_length=50)),
                ('EnglishName_2', models.CharField(max_length=50)),
                ('EnglishName_3', models.CharField(max_length=50)),
                ('EnglishInterpretation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('parentSort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Sort')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Sort'),
        ),
    ]
