# Generated by Django 2.1.5 on 2019-08-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SimplifiedName', models.CharField(max_length=50)),
                ('TraditionalName', models.CharField(blank=True, max_length=50, null=True)),
                ('PinyinName', models.CharField(max_length=50)),
                ('EnglishName_1', models.CharField(max_length=100)),
                ('EnglishName_2', models.CharField(blank=True, max_length=100, null=True)),
                ('EnglishName_3', models.CharField(blank=True, max_length=100, null=True)),
                ('EnglishInterpretation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('parentSort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Sort')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Sort'),
        ),
    ]
