# Generated by Django 2.1.5 on 2019-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190712_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishInterpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TraditionalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
