# Generated by Django 2.1.5 on 2019-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190712_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='EnglishInterpretation',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_2',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_3',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='TraditionalName',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
