# Generated by Django 2.1.5 on 2019-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190712_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
