# Generated by Django 2.1.5 on 2019-07-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190712_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='EnglishInterpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='EnglishName_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='TraditionalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
